### PR TITLE
Added usage

### PR DESCRIPTION
**Pull request by george-angel**

### CODE REVIEW

**Comment by catalin-ilea** [comment]
@george-angel https://golang.org/pkg/os/#Setenv

**Comment by george-angel** [comment]
No:

```
test/cat main.go
package main

import (
        "os"
        "os/exec"
)

func main() {
        cmd := exec.Command("tty")
        out, _ := cmd.Output()

        os.Setenv("GPG_TTY", string(out))
        cmd = exec.Command("env")
        cmd.Stdout = os.Stdout
        cmd.Run()
}
test/go run main.go | grep GPG
GPG_TTY=not a tty
test/
```

**Comment by catalin-ilea** [comment]
```
import (
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("tty")
	cmd.Stdin = os.Stdin
	out, _ := cmd.Output()

	os.Setenv("GPG_TTY", string(out))
	cmd = exec.Command("env")
	cmd.Stdout = os.Stdout
	cmd.Run()
}
```

**Comment by mjgarton** [comment]
instead of os.Setenv, you can probably better use cmd.Env for setting the environment for the specific cmd child process instead of for the whole current process. (disclaimer: I haven't tested this and i have jetlag)

**Pull request merged**
